### ISSUE TITLE
h5适老化（大字版适配）终极方案

### ISSUE THREAD

**Issue by LingYanSi** [LingYanSi/blog#153]
## 字体放大原理
- ios可通过`text-size-adjust`进行字体放大，但此属性在android上无效。
- android放大字体可参考[此链接](https://stackoverflow.com/questions/21694306/how-to-set-text-size-in-webview-in-android)

字体放大很简单，麻烦的是如何屏蔽字体放大。对于新业务可以通过合理项目架构设计来适应字体大小，但对于存在时间较长、历史包袱较重的项目，粗暴的进行字体放大，会导致部分元素布局乱掉。因此我们需要寻求一种方案，以屏蔽字体放大

经过验证，字体放大会影响两个属性的真机表现：`font-size、line-height`

### android
因为安卓的字体放大并不是通过css进行控制的，因此我们也不能使用css进行屏蔽。

但我们可以换一种思路，浏览器对字体进行了同等比例的放大，那我们只需要在css层面进行同等比例的缩小即可。

### ios
可以通过`text-size-adjust: none`进行屏蔽，但是为了方案的一致性，我们选择与android一样的方案。

实际业务上字体放大比例会有多个级别的选项，比如`1.1 1.2 1.3 1.4`，但我们不可能把代码写成如下的样子

```less
.no-zoom-btn {
    font-size: 12px;
    line-height: 20px;
}

html.font-zoom-11 .no-zoom-btn {
    font-size: (12px / 1.1);
    line-height: (20px / 1.2);
}

html.font-zoom-12 .no-zoom-btn {
    font-size: (12px / 1.2);
    line-height: (20px / 1.2);
}

html.font-zoom-13 .no-zoom-btn {
    font-size: (12px / 1.3);
    line-height: (20px / 1.3);
}

html.font-zoom-14 .no-zoom-btn {
    font-size: (12px / 1.4);
    line-height: (20px / 1.4);
}
```

聪明如你，一定想到了使用less的函数来对逻辑进行抽象（sass或者其他css预处理语言都有类似解决方案）

```less
.disableZoomFont(@font) {
    html.font-zoom-11 & {
        font-size: (@font / 1.1);
    }
    html.font-zoom-12 & {
        font-size: (@font / 1.2);
    }
    html.font-zoom-13 & {
        font-size: (@font / 1.3);
    }
    html.font-zoom-11 & {
        font-size: (@font / 1.4);
    }
}
.disableZoomLineHeight(font) {
    html.font-zoom-11 & {
        line-height: (@font / 1.1);
    }
    html.font-zoom-12 & {
        line-height: (@font / 1.2);
    }
    html.font-zoom-13 & {
        line-height: (@font / 1.3);
    }
    html.font-zoom-11 & {
        line-height: (@font / 1.4);
    }
}
.no-zoom-btn {
    .disableZoomFont(12px);
    .disableZoomLineHeight(20px);
}
```
