### ISSUE TITLE
font-family

### ISSUE THREAD

**Issue by LingYanSi** [LingYanSi/blog#163]
windows default font list
https://learn.microsoft.com/en-us/typography/fonts/windows_11_font_list

chrome font setting
```
chrome://settings/fonts
```

如果在页面中设置了字体如下
```css
body {
   font-family: 字体1, 字体2, sans-serif;
}
```

如果字体1/2存在的话，就使用对应的字体进行渲染
如果字体不存在，则去查找相对应的系统字体，其中在chrome中以下字体拥有独立的设置
```
Standard font
Serif font
Sans-serif font
```

而对于google网页来讲，其字体设置的很简单
```css
font-family: Arial, sans-serif;
```

mac默认字体为`Helvetica`
