### ISSUE TITLE
Fuck Vertical-align

### ISSUE THREAD

**Issue by LingYanSi** [LingYanSi/blog#44]
# 行内元素上下对齐

![qq 20160930172443](https://cloud.githubusercontent.com/assets/8621814/18987127/cef27702-8732-11e6-94f1-888d9d2f32ea.png)
如图所示

``` css
vertical-align: middle;
```

**Comment by LingYanSi** [comment]
## 坑太多

正确姿势
html:

``` html
<div>
    你好吗
    <span>你是谁呢？</span>
    <span class="test">你说的空间是否会卡死</span>
</div>
```

``` css
span{
    vertical-align: center;
}

.test {
    line-height: 1.4;
}
```

这里有几个点需要注意
无法给 `你好吗` 设置vertical-align属性，因此`你好吗`的上下居中需要其他行内元素
vertical-align 只能用在`display: inline/inline-block;` 的元素,即行内元素上
1. 文本节点 + 一个行内元素
   无法上下居中
2. 文本节点 + 多个行内元素，也不能上下居中
   至少一个行内元素的line-height 或者高度大于父元素的行高
3. 多个行内元素 
   至少一个行内元素的line-height 或者高度大于父元素的行高

要注意的是，元素的默认行高一般是小于1.4的值1.2/1.3 etc
