### ISSUE TITLE
简单Markdown编辑器实现

### ISSUE THREAD

**Issue by LingYanSi** [LingYanSi/blog#70]
## 高度自动展开
因为div并不安全，我们使用textarea来接受用户输入，但是textarea高度不会自使用高度，滚动条的体验很糟糕
解决方案之一是，使用pre来代理textarea的宽高，textarea使用绝对定位，pre变高的同时，textarea也就自动变高了，一颗赛艇！！！
```scss
.editor {
        position: relative;
        padding: 0;

        pre, textarea {
            min-height: 1.6em * 3;
            line-height: 1.6;
            // word-wrap: break-word;
            font-size: 14px;
            word-break: break-all;
            white-space: pre-wrap;
            letter-spacing: normal;
            word-spacing: normal;
            border: 1px solid red;
            outline: none;
            box-shadow: none;
            padding: $padding $padding * .6;
        }
        pre {
            visibility: hidden;
        }

        textarea {
            resize: none;
            display: block;
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            box-sizing: border-box;
        }
       
        @at-root {
            .device-ios .editor textarea {
                padding: $padding - 3px $padding * .6 - 3px;
            }
        }
    }
```

```  .device-ios ```用来处理ios下textarea 3px问题
![image](https://user-images.githubusercontent.com/8621814/27168876-1734ad10-51da-11e7-912c-910e0be7a6cc.png)
![image](https://user-images.githubusercontent.com/8621814/27168918-45115ecc-51da-11e7-946d-1d6ae2a1644a.png)
上图发现，textarea的内部是通过shadow dom实现的，并且其padding为3px 💊

因此在style上要对ios进行特殊处理，padding减去3px

另外pre和textarea各自都有自己默认的字体，因此需要在css中，为其设定相同的字体
