### ISSUE TITLE
css奇技淫巧

### ISSUE THREAD

**Issue by LingYanSi** [LingYanSi/blog#98]
# 图片预加载的一种思路

组件状态发生变化的时候，需要切换到另外一张图片。如果在状态更改后再去请求图片，会造成页面闪动。因此需要把图片提前加载进来。

## 使用js加载
```js
function load(time = 0) {
     setTimeout(() => {
        new Image().src = 'img/src'
     }, time)
}
```
js的优势是灵活性强，可以充分控制图片的加载流程，弊端在于还要多写一点js代码，并且很多时候图片的资源路径是写在css/less里面的，可能会多一点重复代码

## 方法二使用css加载
使用css animation来做到图片的延迟加载:-D

```less
@normalDown: "https://cdn.weipaitang.com/static/201712057f6ad537-3072-4c17-b1ae-0975205b71bb-W17H8";
@activeDown: "https://cdn.weipaitang.com/static/2017120592c8c25e-2cef-4f36-90db-8038a136d3c0-W17H8";
@normalUp: "https://cdn.weipaitang.com/static/201712058483c99d-c160-43cd-ae20-510f9959c557-W17H8";
@activeUp: "https://cdn.weipaitang.com/static/2017120566edc367-7f66-43bf-bbb2-5a053996f81e-W17H8";

.preLoadImgs {
    animation: fff .05s 2s;
    @keyframes fff {
        from {
            background: none;
        }
        to {
            background: url("@{normalDown}"), url("@{activeDown}"), url("@{normalUp}"), url("@{activeUp}");
        }
    }
}
```

```jsx
<div className={S.preLoadImgs}></div>
```
